# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06154b7efc95ab7bb61b8e31918c0de1cbeeb9122d62b9e3b0c3c1fe4fccbd225c3e69ad7b3579cd962b4699192d119d63c60aa4bbf4df880d022366f365fb32

test:
  secret_key_base: 8a6407482797447d114a9c291bc48d1cb4c44b5ec6e69db28bf519f943e32f25676f7a31825f8901290a973f191b4a5cf5612bddbf357e6cbfa3406a2863675b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
